# -*- coding: utf-8 -*-
"""Butterworth Low pass & High pass Filter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xwfwFPFP6eOeVh-yl4XHrE2TpanlOb5J
"""

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import cv2
import os
import matplotlib.pyplot as plt

def distance(u, v, M, N):
    return np.sqrt((u - M/2)**2 + (v - N/2)**2)

"""## Butterworth Low Pass Filter"""

def butterworth_lowpass(shape, D0, n):
    M, N = shape
    H = np.zeros((M, N), dtype=np.float32)

    for u in range(M):
        for v in range(N):
            D = distance(u, v, M, N)
            H[u, v] = 1 / (1 + (D / D0)**(2*n))

    return H

"""## Butterworth High Pass Filter"""

def butterworth_highpass(shape, D0, n):
    M, N = shape
    H = np.zeros((M, N), dtype=np.float32)

    for u in range(M):
        for v in range(N):
            D = distance(u, v, M, N)
            if D == 0:
                H[u, v] = 0
            else:
                H[u, v] = 1 / (1 + (D0 / D)**(2*n))

    return H

def apply_filter(img, H):

    f = np.fft.fft2(img)
    fshift = np.fft.fftshift(f)

    # Apply filter
    G = fshift * H

    g_shift = np.fft.ifftshift(G)
    img_back = np.fft.ifft2(g_shift)
    img_back = np.abs(img_back)

    return img_back

folder_path = '/content/drive/MyDrive/Fundas Images'

D0 = 30
n = 2

image_files = [f for f in os.listdir(folder_path) if f.endswith(('.jpg', '.png', '.jpeg'))]

for file in image_files:
    path = os.path.join(folder_path, file)


    img = cv2.imread(path, 0)


    H_low = butterworth_lowpass(img.shape, D0, n)
    H_high = butterworth_highpass(img.shape, D0, n)


    low_img = apply_filter(img, H_low)
    high_img = apply_filter(img, H_high)


    plt.figure(figsize=(12,4))

    plt.subplot(1,3,1)
    plt.imshow(img, cmap='gray')
    plt.title('Original')
    plt.axis('off')

    plt.subplot(1,3,2)
    plt.imshow(low_img, cmap='gray')
    plt.title('Low Pass')
    plt.axis('off')

    plt.subplot(1,3,3)
    plt.imshow(high_img, cmap='gray')
    plt.title('High Pass')
    plt.axis('off')

    plt.suptitle(file)
    plt.show()