# -*- coding: utf-8 -*-
"""Gaussian Low Pass and High Pass filter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HZk7fFZ-q8joKf4NXXfQ_ecNw5eM6foh
"""

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import cv2
import os
import matplotlib.pyplot as plt

def D_uv(u, v, M, N):
    return ((u - M/2)**2 + (v - N/2)**2)**0.5

"""## Gaussian LOW Pass filter"""

def gaussian_lowpass(shape, D0):
    M, N = shape
    H = np.zeros((M, N), dtype=np.float32)

    for u in range(M):
        for v in range(N):
            D = D_uv(u, v, M, N)
            H[u, v] = np.exp(-(D**2) / (2 * (D0**2)))

    return H

"""## Gaussian High Pass filter"""

def gaussian_highpass(shape, D0):
    M, N = shape
    H = np.zeros((M, N), dtype=np.float32)

    for u in range(M):
        for v in range(N):
            D = D_uv(u, v, M, N)
            H[u, v] = 1 - np.exp(-(D**2) / (2 * (D0**2)))

    return H

def apply_filter(img, H):
    f = np.fft.fft2(img)
    fshift = np.fft.fftshift(f)

    G = fshift * H

    g_ishift = np.fft.ifftshift(G)
    img_back = np.fft.ifft2(g_ishift)
    img_back = np.abs(img_back)

    return img_back

folder_path = '/content/drive/MyDrive/Fundas Images'


D0 = 40

files = [f for f in os.listdir(folder_path) if f.lower().endswith(('.jpg','.png','.jpeg'))]

for file in files:
    path = os.path.join(folder_path, file)

    img = cv2.imread(path, 0)

    H_low = gaussian_lowpass(img.shape, D0)
    H_high = gaussian_highpass(img.shape, D0)


    low_img = apply_filter(img, H_low)
    high_img = apply_filter(img, H_high)


    plt.figure(figsize=(12,4))

    plt.subplot(1,3,1)
    plt.imshow(img, cmap='gray')
    plt.title('Original')
    plt.axis('off')

    plt.subplot(1,3,2)
    plt.imshow(low_img, cmap='gray')
    plt.title('Gaussian Low Pass')
    plt.axis('off')

    plt.subplot(1,3,3)
    plt.imshow(high_img, cmap='gray')
    plt.title('Gaussian High Pass')
    plt.axis('off')

    plt.suptitle(file)
    plt.show()